dist: trusty
language: python
python:
  - "2.7"
cache: pip

install:
  - pip install pandocfilters
  - wget https://github.com/jgm/pandoc/releases/download/1.19.2.1/pandoc-1.19.2.1-1-amd64.deb
  - sudo dpkg -i pandoc-1.19.2.1-1-amd64.deb

script:
  - pandoc --version
  - xvfb-run --server-args="-screen 0, 1024x768x24" make

addons:
  apt:
    packages:
      wkhtmltopdf xvfb context
