dist: trusty
language: python
python:
  - "2.7"
cache: pip

install:
  - pip install pandocfilters

script:
  - pandoc --version
  - xvfb-run --server-args="-screen 0, 1024x768x24" make

addons:
  apt:
    packages:
      wkhtmltopdf xvfb context pandoc
